### Python Basics Cheatsheet 

All of these stuff could be found on the web, e.g, Numpy documentation or StackOverFlow. This notebook is a consolidation of some of the nuances or details that is not so easily found for easy reference. 

Preceding each segment would be a markdown cell that indicates what that section contains for easy search and reference.


#### Index
* Timing operations
* Numpy Array Operations
    * Reshape array 
        * [Flatten Ndarray to 1D](#flatten_nd_to_1d)
        * [Reshape array of Ndarray to array of 1d array](#reshape_array_nd_to_array_1d)

In [21]:
import time
j = 0
start = time.clock()
for i in range(100000):
    j += 1
end = time.clock()
print(end-start)


0.010950000000000015


<a id='flatten_nd_to_1d'>Flatten Ndarray to 1D</a>

In [14]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

# np.flatten, copies a into b
b = a.flatten()
b[0] = 9
print('Flatten...')
print("b:", b)
print("a:", a, "\n")

# np.flat, returns a 1D iterator. i.e. by reference
c = a.flat
c[0] = 10
print('Flat...')
print("a:",a)



Flatten...
b: [9 2 3 4 5 6 7 8 9]
a: [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Flat...
a: [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


<a id='reshape_array_nd_to_array_1d'>Reshape array of ndarray to array of 1D</a>

In [15]:
# Reshape array of ndarrays into array of 1D arrays

# (3,2,2)
arr_nd = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(arr_nd.shape)

# (3,4)
arr_1d = np.reshape(arr_nd,(3,4))
print(arr_1d.shape)
print(arr_1d)

(3, 2, 2)
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
